### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#18]
-- Build date: 2017-08-23
CMake Error at strusPattern/3rdParty/hyperscan_build/CMakeLists.txt:92 (message):
  Ragel state machine compiler not found

**Comment by patrickfrey** [comment]
Added ragel as build dependency to packages and 3rdParty install info.

**Comment by andreasbaumann** [comment]
Still getting the same error, I'm missing a 'ragel' directory..

**Comment by andreasbaumann** [comment]
On Archlinux we need a
makedepends=('ragel')
which is there, was not installed on my machine.

Additionally 'depends' needs a 'tre'.
