### ISSUE TITLE
upgrade to boost 1.57

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#19]
When you upgrade to boost 1.57 you have several issues:
- you loose all platforms having older versions (boost 1.53 for instance on Centos 7)
- this means you have to build your own boost versions (like 'strusboost' in OpenSuseBuild)
- now if you upgrade boost in one package, what happens to boost in other packages?
  Having boost 1.53 and 1.57 as 'strusboost' packages results in name clashes (header
  files and library versioning), so you can do something similar to Debian (having
  boost1.53-dev and boost1.57-dev packages). So short, it's most likely easier in terms
  of maintainance to have only one boost version 1.57. I cannot recommend having two
  boost versions floating around..
- now this means 'strusboost' must be upgraded to 1.57 and be built an much more
  platforms (in OpenSuseBuild) as before 1.53, which had to be built only on CentOS_6 and
  SLE_11_SP4, some quite old stable Linux distributions.
- adding boost (or as a matter of fact all git submodules recently appearing like lua, fmt) heavily
  increases check-out times and build times, so I don't think, this is a very good way.

**Comment by patrickfrey** [comment]
All strus projects are depending on boost >= 1.57 now.
