### ISSUE TITLE
matches containing non-printables using -K parameter

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#20]
For instance matching newlines results in distorted output:

```
5 [19132] : 11 PATTERN_LOSS  Ass


6 [20397] : 48 PATTERN_BOTH             Both
```

**Comment by patrickfrey** [comment]
How should I solve it? With an option to encode the output for example?

**Comment by andreasbaumann** [comment]
Good question. The only real problem is newline matches. I wouldn't fix it, I'll work around it..

**Comment by patrickfrey** [comment]
Fixed strusPatternMatcher: Replacing end of line and control characters by spaces in strusPatternMatcher output
