### ISSUE TITLE
error message from hyperscan

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#22]
```
doc1.txt: failed to scan for tokens with char regex match automaton, error calling hyperscan match event handler: size of matched term out of range"
```

Sadly I don't know what causes it and I cannot provide a test case.

**Comment by patrickfrey** [comment]
It is a strusPattern error message in the lexer. It is issued when the length of a lexem matched by a regular expression exceeds 64K. I did not expect regular expressions matching tokens of this size.
Or it is a corruption of some sort.

**Comment by patrickfrey** [comment]
It would be easy to change. I am just curious, how matches can get so big.

**Comment by andreasbaumann** [comment]
Bad data helps. :-)
I suspect a huge token of some sort containing a '@' matching to a very big string containing '@'.

**Comment by andreasbaumann** [comment]
From my point it's ok: I feed garbage, I get a proper error message..
