### ISSUE TITLE
extension of variable assignment

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#35]
I would like to set a constant attribute of something not appearing in the text, for instance:

```
Rule1 = sequence_imm( first = WORD, last = WORD, type = "person" );
Rule2 = sequence_imm( name = WORD, type = "company" );
```

**Comment by patrickfrey** [comment]
This is an interesting idea.

Currently, a result string can only be assigned to the result of a subexpression or of a rule.
It has to be investigated if this feature is really needed or just a requirement that arose out of the missing of format strings.

**Comment by andreasbaumann** [comment]
This is exacly the case, this can be done in this case with a format string.
