### ISSUE TITLE
undefined token classes can be referenced in rules, no warning

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#36]
```
WORDS = /\b(\w+)\b;

Rule = any( WORD );
```

No error or warning is issued, rule just never matches.

**Comment by patrickfrey** [comment]
You can enforce the compiler to issue an error for unresolved symbols.

%MATCHER strict

But it is not intended to make this the default.
Warnings exist only as debug messages. More work has to be done here, I agree.
