### ISSUE TITLE
mapping extracted attribute values

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#38]
```
Person             = sequence_imm( last = WORD, COMMA, first = WORD, COMMA, map_f( nation ) = WORD "deutscher", WORD "Staatsangehöriger", COMMA, WORD "in", wohnort = WORD );
```

map_f is a function to map "deutscher" to "DE" or so.

**Comment by patrickfrey** [comment]
There exist now format strings for the result and for sub expressions.

http://www.project-strus.net/introduction_struspattern.htm [Formatting pattern matcher results]

Nation              = sequence_imm( nation = WORD "deutscher", WORD "Staatsangehöriger" ) ["DE"];
Person             = sequence_imm( 
                                       last = WORD, 
                                       first = WORD, 
                                       nation = Nation );

The String in square brackets is a constant in this example "DE".
It can also contain references to variables that are substituted with the values represented by these variables.
