### ISSUE TITLE
make install and hyperscan install to /usr/local/lib

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#4]
instead of INSTALL_PREFIX, i.e. /usr/local/lib/strus

**Comment by andreasbaumann** [comment]
additionally developer liraryes like `libhs.a` or header files are installed.

I'm opting not to install anything from hyperscan and just install a shared libary
libstrus_hs_runtime.so or to link statically.

**Comment by patrickfrey** [comment]
Actually I do not need any static libraries from Hyperscan. I would like to get rid of it

**Comment by andreasbaumann** [comment]
Now libhs.so.4 is missing:

```
ERROR error failed to load module modstrus_analyzer_pattern: [#236] error loading module '/usr/local/lib/strus/modules/modstrus_analyzer_pattern.so': libhs.so.4: cannot open shared object file: No such file or directory
```

**Comment by andreasbaumann** [comment]
```
ERROR error failed to load module modstrus_analyzer_pattern: [#236] error loading module '/usr/local/lib/strus/modules/modstrus_analyzer_pattern.so': libhs.so.4: cannot open shared object file: No such file or directory
```

find /usr/local/ -name libhs.so.4
/usr/local/lib64/libhs.so.4

**Comment by andreasbaumann** [comment]
This is on Archlinux, which does not have a lib64!

**Comment by andreasbaumann** [comment]
As hyperscan is no longer embedded into strusPattern and has to build beforehand, this
is no longer a problem. Closing.
