### ISSUE TITLE
Support for an ANY token

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#40]
For instance a rule matching everything inside two brakets:

```
WORD ^1            : /([\p{L}\d]+)/;
COMMA              : /,/;
OPEN_BRAKET        : /\(/;
CLOSE_BRAKET       : /\)/;

InsideBrakets = sequence_imm( OPEN_BRAKET, word[] = ANY, CLOSE_BRAKET );
```

**Comment by patrickfrey** [comment]
An ANY token is not possible to implement. You need to define what a token is, e.g.
           ANY : /\b.*\b/;
This example does not work with Unicode though.

There is no way for StrusPattern to determine what an ANY token could be, except a default definition. That's the nature of a system, that allows you to define whatever you want as lexical tokenization. You could also define pairs of characters or trigrams as lexemes. What could ANY mean in this context? Any default ANY token definition would be misleading. 

A default ANY lexeme also interferes with the ordinal position counting of a rule set. Ordinal positions define the meaning of range specifiers (defining the maximum distance of items, counted as the number of lexical tokens occurring in between plus one for the second item itself) and immediate ('.._imm'). So you have always to think about it and you need an operation to explicitly switch it off if this interference is disturbing.

**Comment by andreasbaumann** [comment]
Yes, agreed. In another bug I had another idea, sort of subrules:

```
Person = sequence_imm( first = any ( WORD, LOWERCASEWORD, UPPERCASEWORD ) );
```

This avoids cluttering the output with tons of helper rule output as in:

```
AWord = any ( WORD, LOWERCASEWORD, UPPERCASEWORD );
Person = sequence_imm( first = AWord );
```

Alternatively there would also be the idea of declaring public and private tokens, rules
and to export only the public ones.

**Comment by patrickfrey** [comment]
Subrules should be

      Person = sequence_imm( first = any ( WORD, LOWERCASEWORD, UPPERCASEWORD ) );

 possible.  there is a bug if not.

**Comment by patrickfrey** [comment]
Private rules are starting with a dot:

.AWord = any ( WORD, LOWERCASEWORD, UPPERCASEWORD );
Person = sequence_imm( first = AWord );
